import { Article } from "./types"

export const articles: Article[] = [
  {
    id: "1",
    title: "OpenAI Announces GPT-5 with Revolutionary Reasoning Capabilities",
    source: "TechCrunch",
    summary: "OpenAI has unveiled GPT-5, featuring significant improvements in multi-step reasoning, code generation, and factual accuracy. The model demonstrates near-human performance on complex scientific benchmarks, representing a fundamental shift in how large language models approach problem-solving tasks.",
    publishedAt: "2026-07-22T10:00:00Z",
    url: "https://techcrunch.com/example",
    tags: ["OpenAI", "GPT-5", "LLM"],
    slug: "openai-gpt5-announcement",
    category: "Research",
    imageUrl: "https://picsum.photos/seed/openai-gpt5/1200/630",
    readingTime: 6
  },
  {
    id: "2",
    title: "Google DeepMind Solves New Protein Folding Challenge",
    source: "Nature",
    summary: "DeepMind's latest AlphaFold iteration can now predict protein interactions with membrane-bound complexes, opening new avenues for drug discovery and personalized medicine. The breakthrough represents a decade of computational biology research coming to fruition.",
    publishedAt: "2026-07-21T14:30:00Z",
    url: "https://nature.com/example",
    tags: ["DeepMind", "Protein Folding", "Biotech"],
    slug: "deepmind-protein-folding",
    category: "Research",
    imageUrl: "https://picsum.photos/seed/deepmind-protein/1200/630",
    readingTime: 8
  },
  {
    id: "3",
    title: "EU AI Act Enforcement Begins: What Companies Need to Know",
    source: "Reuters",
    summary: "The European Union's comprehensive AI regulation officially takes effect, requiring companies to meet transparency and safety requirements for high-risk AI systems. Fines of up to 6% of global revenue await non-compliant organizations.",
    publishedAt: "2026-07-20T09:15:00Z",
    url: "https://reuters.com/example",
    tags: ["Regulation", "EU AI Act", "Policy"],
    slug: "eu-ai-act-enforcement",
    category: "Policy",
    imageUrl: "https://picsum.photos/seed/eu-ai-act/1200/630",
    readingTime: 5
  },
  {
    id: "4",
    title: "Tesla Optimus Robot Achieves Warehouse Autonomy",
    source: "Bloomberg",
    summary: "Tesla's humanoid robot Optimus has successfully completed a 30-day trial in Amazon warehouses, performing complex pick-and-place tasks with 99.2% accuracy. The milestone signals a turning point for commercial humanoid robotics at scale.",
    publishedAt: "2026-07-19T16:45:00Z",
    url: "https://bloomberg.com/example",
    tags: ["Tesla", "Robotics", "Automation"],
    slug: "tesla-optimus-warehouse",
    category: "Hardware",
    imageUrl: "https://picsum.photos/seed/tesla-optimus/1200/630",
    readingTime: 4
  },
  {
    id: "5",
    title: "Anthropic Introduces Constitutional AI 2.0",
    source: "MIT Technology Review",
    summary: "Anthropic's new framework enables AI systems to self-correct harmful outputs in real-time while maintaining helpfulness, marking a significant advance in AI safety. The system uses a novel set of principles to guide model behavior without human feedback on every interaction.",
    publishedAt: "2026-07-18T11:20:00Z",
    url: "https://technologyreview.com/example",
    tags: ["Anthropic", "AI Safety", "Constitutional AI"],
    slug: "anthropic-constitutional-ai-2",
    category: "Research",
    imageUrl: "https://picsum.photos/seed/anthropic-cai2/1200/630",
    readingTime: 7
  },
  {
    id: "6",
    title: "NVIDIA Announces Next-Gen AI Chips with 10x Performance",
    source: "The Verge",
    summary: "NVIDIA's Blackwell Ultra architecture delivers unprecedented performance for large language model training, reducing costs by 80% compared to previous generations. The new chip line is set to reshape the economics of AI infrastructure for enterprises globally.",
    publishedAt: "2026-07-17T08:00:00Z",
    url: "https://theverge.com/example",
    tags: ["NVIDIA", "Hardware", "Chips"],
    slug: "nvidia-blackwell-ultra",
    category: "Hardware",
    imageUrl: "https://picsum.photos/seed/nvidia-blackwell/1200/630",
    readingTime: 5
  },
  {
    id: "7",
    title: "AI-Powered Drug Discovery Leads to New Antibiotic",
    source: "Science",
    summary: "Researchers at MIT have used machine learning to discover a novel antibiotic effective against drug-resistant bacteria, potentially saving millions of lives. The model screened over 100 million compounds in days — a task that would have taken decades by traditional methods.",
    publishedAt: "2026-07-16T13:30:00Z",
    url: "https://science.org/example",
    tags: ["Healthcare", "Drug Discovery", "Research"],
    slug: "ai-antibiotic-discovery",
    category: "Research",
    imageUrl: "https://picsum.photos/seed/ai-drug-discovery/1200/630",
    readingTime: 6
  },
  {
    id: "8",
    title: "Microsoft Copilot Now Integrated into All Office Applications",
    source: "Wired",
    summary: "Microsoft's AI assistant Copilot is now embedded across Word, Excel, PowerPoint, and Outlook, fundamentally changing how knowledge workers interact with productivity software. Early data suggests a 40% reduction in time spent on routine tasks.",
    publishedAt: "2026-07-15T10:45:00Z",
    url: "https://wired.com/example",
    tags: ["Microsoft", "Copilot", "Productivity"],
    slug: "microsoft-copilot-office",
    category: "Industry",
    imageUrl: "https://picsum.photos/seed/ms-copilot/1200/630",
    readingTime: 4
  },
  {
    id: "9",
    title: "China's AI Industry Reaches New Milestone in Autonomous Vehicles",
    source: "South China Morning Post",
    summary: "Chinese tech giants Baidu and Alibaba have deployed fully autonomous ride-hailing fleets in 50 cities, surpassing Western competitors in scale. The rollout covers over 10 million rides in the past quarter with zero reported serious incidents.",
    publishedAt: "2026-07-14T07:15:00Z",
    url: "https://scmp.com/example",
    tags: ["China", "Autonomous Vehicles", "Industry"],
    slug: "china-autonomous-vehicles",
    category: "Industry",
    imageUrl: "https://picsum.photos/seed/china-av/1200/630",
    readingTime: 5
  },
  {
    id: "10",
    title: "Breakthrough in Quantum-AI Hybrid Computing",
    source: "Nature Physics",
    summary: "IBM and Google jointly announce a quantum processor that can accelerate specific AI workloads by 1000x, bridging the gap between quantum and classical computing. The prototype demonstrates stable entanglement at room temperature for the first time.",
    publishedAt: "2026-07-13T15:00:00Z",
    url: "https://nature.com/example",
    tags: ["Quantum Computing", "IBM", "Google"],
    slug: "quantum-ai-hybrid",
    category: "Research",
    imageUrl: "https://picsum.photos/seed/quantum-ai/1200/630",
    readingTime: 9
  },
  {
    id: "11",
    title: "AI-generated Art Wins Prestigious Photography Award",
    source: "The Guardian",
    summary: "An AI-generated image has won the Sony World Photography Award, sparking debate about the future of creative arts and authorship in the age of generative AI. The decision has split the creative community between embracing the technology and calling for separate competition categories.",
    publishedAt: "2026-07-12T12:00:00Z",
    url: "https://theguardian.com/example",
    tags: ["Art", "Generative AI", "Ethics"],
    slug: "ai-art-photography-award",
    category: "Policy",
    imageUrl: "https://picsum.photos/seed/ai-art-award/1200/630",
    readingTime: 4
  },
  {
    id: "12",
    title: "Startup Raises $500M for AI-powered Climate Modeling",
    source: "Forbes",
    summary: "Climate AI has secured massive funding to build the world's most accurate climate prediction models, helping governments and businesses prepare for extreme weather events. The models already outperform traditional meteorological systems by 35% in 90-day forecasting accuracy.",
    publishedAt: "2026-07-11T09:30:00Z",
    url: "https://forbes.com/example",
    tags: ["Climate", "Startup", "Funding"],
    slug: "ai-climate-modeling-funding",
    category: "Industry",
    imageUrl: "https://picsum.photos/seed/ai-climate/1200/630",
    readingTime: 5
  }
]
